version: 1.2
workflows:
  - name: IsoQuantMakeDB
    subclass: WDL
    primaryDescriptorPath: /LR-tools/IsoQuant/IsoQuantMakeDB.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: IsoQuantQuantify
    subclass: WDL
    primaryDescriptorPath: /LR-tools/IsoQuant/IsoQuantQuantify.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: LIQAQuantify
    subclass: WDL
    primaryDescriptorPath: /LR-tools/LIQA/liqaQuantify.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: LongRNAqcFromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/LongRNAqc/LongRNAqcFromBAM.wdl
  - name: LongRNAqcPlusFromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/LongRNAqc/LongRNAqcPlusFromBAM.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: Minimap2_LR
    subclass: WDL
    primaryDescriptorPath: /LR-tools/minimap2_LR/minimap2_LR.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: LongRNAqcPlotting
    subclass: WDL
    primaryDescriptorPath: /LR-tools/LongRNAqc/LongRNAqcPlotting.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: LongRNAqc_readAccuracyAnalyzer
    subclass: WDL
    primaryDescriptorPath: /LR-tools/LongRNAqc/LongRNAqc_readAccuracyAnalyzer.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: Sqanti3FromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/sqanti3/sqanti3FromBAM.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: StringTieMerge
    subclass: WDL
    primaryDescriptorPath: /LR-tools/stringtie_merge/stringtie_merge_and_reestimate.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: BamToFastq
    subclass: WDL
    primaryDescriptorPath: /LR-tools/utilities/BamToFastq.wdl
    authors:
      - name: bhaas

  - name: Duplex_read_finder
    subclass: WDL
    primaryDescriptorPath: /misc_tools/duplex_read_finding/Duplex_read_finder.wdl
    authors:
      - name: bhaas

  - name: Samtools_DownsampleBam
    subclass: WDL
    primaryDescriptorPath: /misc_tools/Samtools_DownsampleBam/Samtools_DownsampleBam.wdl
    authors:
      - name: bhaas

  - name: BamToFastqGz
    subclass: WDL
    primaryDescriptorPath: /misc_tools/BamToFastq/BamToFastq.wdl
    authors:
      - name: bhaas

  - name: BamErrorRates
    subclass: WDL
    primaryDescriptorPath: /misc_tools/bam_error_rates/BamErrorRates.wdl
    authors:
      - name: bhaas

  - name: PartitionSCbamByID
    subclass: WDL
    primaryDescriptorPath: /misc_tools/partitioning_bam_by_id/partitioning_bam_by_id.wdl
    authors:
      - name: akhorgad
      
  - name: LRAA_SC_generate_sparseM
    subclass: WDL
    primaryDescriptorPath: /misc_tools/LRAA-sc-post-processing/LRAA-sc-post-processing.wdl
    authors:
      - name: akhorgad
  
  - name: CTAT_LRF_add_metadata
    subclass: WDL
    primaryDescriptorPath: /misc_tools/ctat-lr-fusion_post-processing/fusion_barcode_processing.wdl
    authors:
      - name: akhorgad

  - name: split_fusions_by_id
    subclass: WDL
    primaryDescriptorPath: /misc_tools/ctat-lr-fusion_post-processing/split_fusions_by_patient.wdl
    authors:
      - name: akhorgad
      
  - name: readcounts_CB_from_bam
    subclass: WDL
    primaryDescriptorPath: /misc_tools/extract_barcode_readcounts_from_aligned_bam/scBarcodeCounting.wdl
    authors:
      - name: akhorgad

  - name: readlengths_from_bam
    subclass: WDL
    primaryDescriptorPath: /misc_tools/extract_readcounts_from_aligned_bam/countLRReadLengths.wdl
    authors:
      - name: akhorgad
      
  - name: LRAA_build_or_assign_seurat_cluster
    subclass: WDL
    primaryDescriptorPath: /misc_tools/LRAA-sc-post-processing/LRAA_build_or_assign_seurat_cluster.wdl
    authors:
      - name: akhorgad     

